import { execFileSync } from "node:child_process"
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, realpathSync } from "node:fs"
import { tmpdir } from "node:os"
import { dirname, join } from "node:path"
import { afterEach, beforeEach, expect, it } from "vitest"
import { projectDependencies, exactProjectVersion } from "../src/project.js"
import { inventoryWorkspace } from "../src/workspace/inventory.js"

let root: string
const put = (path: string, value: string | object) => {
  mkdirSync(dirname(join(root, path)), { recursive: true })
  writeFileSync(join(root, path), typeof value === "string" ? value : JSON.stringify(value))
}
beforeEach(() => {
  root = realpathSync(mkdtempSync(join(tmpdir(), "typelatch-lockfiles-")))
  execFileSync("git", ["init", "-q", root])
  put("package.json", { dependencies: { effect: "^3.0.0" } })
})
afterEach(() => rmSync(root, { recursive: true, force: true }))

const fixtures = [
  ["pnpm-lock.yaml", `lockfileVersion: '9.0'
importers:
  .:
    dependencies:
      effect:
        specifier: ^3.0.0
        version: 3.22.1
packages:
  effect@3.22.1:
    resolution: {integrity: sha512-fixture}
  helper@1.0.0:
    resolution: {integrity: sha512-helper}
snapshots: {}
`],
  ["bun.lock", `{
  // Bun JSONC accepts comments and trailing commas.
  "lockfileVersion": 1,
  "workspaces": {"": {"dependencies": {"effect": "^3.0.0"}}},
  "packages": {
    "effect": ["effect@3.22.1", "", {}, "sha512-fixture"],
    "helper": ["helper@1.0.0", "", {}, "sha512-helper"],
  },
}`],
  ["yarn.lock", `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

effect@^3.0.0, effect@^3.22.0:
  version "3.22.1"
  resolved "https://registry.yarnpkg.com/effect/-/effect-3.22.1.tgz"
  integrity sha512-fixture

helper@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/helper/-/helper-1.0.0.tgz"
  integrity sha512-helper
`],
  ["yarn.lock", `__metadata:
  version: 8
"effect@npm:^3.0.0":
  version: 3.22.1
  resolution: "effect@npm:3.22.1"
  checksum: 10c0/not-an-npm-integrity
"helper@npm:^1.0.0":
  version: 1.0.0
  resolution: "helper@npm:1.0.0"
`],
] as const

it.each(fixtures)("reads direct and transitive identities from %s", async (file, content) => {
  put(file, content)
  expect(await projectDependencies(root)).toEqual([{ name: "effect", version: "3.22.1" }])
  expect(await exactProjectVersion(root, "effect")).toBe("3.22.1")
  const result = await inventoryWorkspace(root, true, new AbortController().signal)
  expect(result.dependencies).toEqual(expect.arrayContaining([
    expect.objectContaining({ package: "effect", version: "3.22.1", identity: "lockfile", installed: false }),
    expect.objectContaining({ package: "helper", version: "1.0.0", identity: "lockfile", installed: false }),
  ]))
  expect(result.issues).toEqual([])
  expect(result.files.find(item => item.path === join(root, file))?.searchable).toBe(false)
  expect(result.dependencies.find(item => item.package === "effect")?.integrity).toBe(content.includes("checksum:") ? undefined : "sha512-fixture")
})

// Generated with pnpm 12.9.1, Bun 1.3.9 and Yarn 1.22.22, with lifecycle scripts disabled.
it.each(["pnpm-lock.yaml", "bun.lock", "yarn.lock"])("reads generated %s with aliases, workspaces and multiple versions", async file => {
  const { readFileSync } = await import("node:fs")
  put(file, readFileSync(new URL(`./fixtures/lockfiles/${file}`, import.meta.url), "utf8"))
  put("package.json", { dependencies: { "is-odd": "3.0.1", alias: "npm:is-number@6.0.0" } })
  put("packages/app/package.json", { name: "app", dependencies: { "is-number": "7.0.0" } })
  expect(await projectDependencies(root)).toEqual([
    { name: "is-number", version: "6.0.0", alias: "alias" }, { name: "is-odd", version: "3.0.1" },
  ])
  expect(await exactProjectVersion(root, "alias")).toBe("6.0.0")
  expect(await projectDependencies(join(root, "packages/app"))).toEqual([{ name: "is-number", version: "7.0.0" }])
  const inventory = await inventoryWorkspace(root, true, new AbortController().signal)
  expect(inventory.issues).toEqual([])
  expect(inventory.dependencies.map(item => `${item.package}@${item.version}`).sort()).toEqual(["is-number@6.0.0", "is-number@7.0.0", "is-odd@3.0.1"])
})

it("uses the Bun workspace installation instead of another hoisted version", async () => {
  put("package.json", { name: "fixture", dependencies: { effect: "3.22.1" } })
  put("packages/app/package.json", { name: "@scope/app", dependencies: { effect: "3.20.0" } })
  put("bun.lock", { lockfileVersion: 1, workspaces: { "packages/app": { name: "@scope/app" } }, packages: {
    effect: ["effect@3.22.1", "", {}, "sha512-root"],
    "@scope/app/effect": ["effect@3.20.0", "", {}, "sha512-nested"],
    "@scope/app": ["@scope/app@workspace:packages/app"],
  } })
  expect(await projectDependencies(join(root, "packages/app"))).toEqual([{ name: "effect", version: "3.20.0" }])
})

it.each([5.4, 6, 9])("handles pnpm schema %s and peer contexts", async version => {
  const key = version === 5.4 ? "/effect/3.22.1_peer@1.0.0" : version === 6 ? "/effect@3.22.1(peer@1.0.0)" : "effect@3.22.1"
  const ref = version === 5.4 ? "3.22.1_peer@1.0.0" : "3.22.1(peer@1.0.0)"
  put("pnpm-lock.yaml", `lockfileVersion: '${version}'\nimporters:\n  .:\n    dependencies:\n      effect:\n        version: '${ref}'\npackages:\n  '${key}':\n    resolution: {integrity: sha512-fixture}\n`)
  expect(await exactProjectVersion(root, "effect")).toBe("3.22.1")
})

it("reads the project document from a pnpm lockfile with an environment document", async () => {
  put("pnpm-lock.yaml", `---\nlockfileVersion: '9.0'\nimporters: {}\npackages: {}\n---\n${fixtures[0][1]}`)
  expect(await projectDependencies(root)).toEqual([{ name: "effect", version: "3.22.1" }])
})

it.each([1, 2, 3])("preserves npm schema %s and shrinkwrap priority", async version => {
  put("package-lock.json", { lockfileVersion: 3, packages: { "node_modules/effect": { version: "9.0.0" } } })
  put("npm-shrinkwrap.json", { lockfileVersion: version, ...(version === 1 ? { dependencies: { effect: { version: "3.22.1" } } } : { packages: { "node_modules/effect": { version: "3.22.1" } } }) })
  expect(await exactProjectVersion(root, "effect")).toBe("3.22.1")
})

it("reports ambiguity and honors packageManager", async () => {
  put("pnpm-lock.yaml", fixtures[0][1])
  put("bun.lock", fixtures[1][1])
  await expect(projectDependencies(root)).rejects.toThrow("Ambiguous lockfiles")
  let inventory = await inventoryWorkspace(root, true, new AbortController().signal)
  expect(inventory.dependencies).toEqual([])
  expect(inventory.issues.join(" ")).toContain("Ambiguous lockfiles")
  put("package.json", { packageManager: "pnpm@10.0.0", dependencies: { effect: "^3.0.0" } })
  expect(await exactProjectVersion(root, "effect")).toBe("3.22.1")
  inventory = await inventoryWorkspace(root, true, new AbortController().signal)
  expect(inventory.issues).toEqual([])
})

it("rejects malformed, unsupported and binary locks without falling back to npm", async () => {
  put("bun.lock", "{ broken")
  await expect(exactProjectVersion(root, "effect")).rejects.toThrow("Invalid bun.lock")
  put("bun.lock", { lockfileVersion: 999, packages: {} })
  await expect(projectDependencies(root)).rejects.toThrow("Unsupported Bun lockfile version")
  rmSync(join(root, "bun.lock"))
  writeFileSync(join(root, "bun.lockb"), Buffer.from([0, 255]))
  await expect(projectDependencies(root)).rejects.toThrow("Unsupported binary bun.lockb")
  expect((await inventoryWorkspace(root, true, new AbortController().signal)).issues.join(" ")).toContain("Unsupported binary bun.lockb")
})

it("does not substitute another Yarn version when the requested descriptor is missing", async () => {
  put("yarn.lock", fixtures[3][1])
  put("package.json", { dependencies: { effect: "^4.0.0" } })
  await expect(projectDependencies(root)).rejects.toThrow("No exact locked registry identity")
})

it("installed identities override direct lock candidates without inheriting mismatched integrity", async () => {
  put("pnpm-lock.yaml", fixtures[0][1])
  put("node_modules/effect/package.json", { name: "effect", version: "4.0.0" })
  const inventory = await inventoryWorkspace(root, true, new AbortController().signal)
  const installed = inventory.dependencies.find(item => item.installed)
  expect(installed).toMatchObject({ package: "effect", version: "4.0.0", identity: "installed" })
  expect(installed?.integrity).toBeUndefined()
  expect(inventory.issues.join(" ")).toContain("Installed dependency differs from lockfile")
})

it("prefers Bun text over a remaining binary lock", async () => {
  put("bun.lock", fixtures[1][1])
  writeFileSync(join(root, "bun.lockb"), Buffer.from([0, 255]))
  expect(await exactProjectVersion(root, "effect")).toBe("3.22.1")
  expect((await inventoryWorkspace(root, true, new AbortController().signal)).issues).toEqual([])
})

it("skips local Yarn workspaces and preserves optional dependencies", async () => {
  put("package.json", { optionalDependencies: { effect: "^3.0.0" }, dependencies: { local: "workspace:*" } })
  put("packages/local/package.json", { name: "local", version: "1.0.0" })
  put("yarn.lock", `${fixtures[3][1]}\n"local@workspace:*":\n  version: 0.0.0-use.local\n  resolution: "local@workspace:packages/local"\n`)
  expect(await projectDependencies(root)).toEqual([{ name: "effect", version: "3.22.1" }])
  expect((await inventoryWorkspace(root, true, new AbortController().signal)).issues).toEqual([])
})

it("does not claim patched pnpm artifacts are registry packages", async () => {
  put("pnpm-lock.yaml", `${fixtures[0][1]}\npatchedDependencies:\n  effect@3.22.1:\n    hash: example\n    path: patches/effect.patch\n`)
  await expect(projectDependencies(root)).rejects.toThrow("No exact locked registry identity")
  const inventory = await inventoryWorkspace(root, true, new AbortController().signal)
  expect(inventory.dependencies.some(item => item.package === "effect")).toBe(false)
  expect(inventory.issues.join(" ")).toContain("Unsupported pnpm package")
})
